apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  template:
    metadata:
      name: web-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-app
            topologyKey: kubernetes.io/hostname            
      containers:
        - name: web-app
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
            limits:
              memory: "5000Mi"
              cpu: "3"
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 3003
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 35

